spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 4
  batch:
    initialize-schema: always
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
