apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-periodic-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: my-periodic-job
              image: localhost:5000/benas/sbk:v0.1
              env:
                - name: DB_URL
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: db.url
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: db.username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: db.password
