apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: my-job
          image: localhost:5000/benas/sbk:v0.1
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db.url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db.password
