apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # base64 of "jdbc:h2:tcp://192.168.1.53/~/testdb" and "sa" ($>echo -n ".." | base64)
  db.url: amRiYzpoMjp0Y3A6Ly8xOTIuMTY4LjEuNTMvfi90ZXN0ZGI=
  db.username: c2E=
  db.password: c2E=
